---
title: "Parenting Project - Database exploration"
author: "Mike & Emily"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: true
number_sections: true
runtime: shiny

---
```{r}
knitr::opts_chunk$set(fig.width=8, fig.height=5, 
                      echo=TRUE, warning=FALSE, message=FALSE, cache=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(langcog))
library(stringr)
library(tidyr)
library(ggrepel)
library(shiny)
theme_set(theme_bw())

load("kinedu_all_processed_3-11-16.RData")
```

One panel. 

```{r}
target_cat <- "touch"
plot_data <- filter(ms, cat_name == target_cat)

label_data <- plot_data %>% 
  group_by(eng_desc) %>% 
  summarise(answer = median(answer), 
            age_months = median(age_months))

ggplot(plot_data,
       aes(x = age_months, y = answer, col = eng_desc)) + 
  geom_jitter(aes(size = n), width = .3, height = 0) + 
  geom_smooth(se=FALSE, aes(weight = n), method="loess") + 
  scale_colour_solarized(guide=FALSE) +
  scale_fill_solarized(guide=FALSE) +
  ylim(c(0,1)) + 
  xlim(c(0,24)) + 
  geom_label_repel(data = label_data, aes(fill = eng_desc, 
                                          label = eng_desc), 
                   force = 4, size = 3,
                   color = 'white',
                   box.padding = unit(0.25, "lines"),
                   point.padding = unit(0.5, "lines"))
```

Multi-panel.

```{r}
plot_data <- filter(ms, cat_name %in% c("cognitive","crawl","smile","walk"))

label_data <- plot_data %>% 
  group_by(cat_name, eng_desc) %>% 
  summarise(answer = median(answer), 
            age_months = median(age_months))

ggplot(plot_data,
       aes(x = age_months, y = answer, col = eng_desc)) + 
  geom_jitter(aes(size = n), width = .3, height = 0) + 
  facet_wrap(~cat_name) + 
  geom_smooth(se=FALSE, aes(weight = n), method="loess") + 
  scale_colour_solarized(guide=FALSE) + 
  scale_fill_solarized(guide=FALSE) + 
  ylim(c(0,1)) + 
  xlim(c(0,24)) + 
#   geom_label(data = label_data, aes(fill = eng_desc, 
#                                     label = eng_desc), 
#              col = "white") 
  geom_label_repel(data = label_data, aes(fill = eng_desc, 
                                          label = eng_desc), 
                   force = 8, size = 2,
                   color = 'white',
                   box.padding = unit(0.25, "lines"),
                   point.padding = unit(0.5, "lines"))
```

Interactive by description. 

```{r, cache=FALSE}
ms$eng_desc <- factor(ms$eng_desc)

shinyApp(
  ui = fluidPage(
    selectizeInput("eng_descs", "Labels", #selected = c("Shakes objects"),
                   choices = gsub("[^[:alnum:] ]","",unique(ms$eng_desc)), 
                   multiple=TRUE),
    plotOutput("descplot")
  ),
  
  server = function(input, output) {
    output$descplot <- renderPlot({
      ggplot(filter(ms, eng_desc %in% input$eng_descs),
             aes(x = age_months, y = answer, col = eng_desc, size = n)) + 
        geom_point() + 
        geom_smooth(se=FALSE, span=4) + 
        scale_colour_solarized(guide=FALSE) + 
        ylim(c(0,1)) + 
        xlim(c(0,24)) + 
        ggrepel::geom_text_repel(data = filter(ms, eng_desc %in% input$eng_descs) %>% 
                                   group_by(eng_desc) %>% 
                                   filter(age_months == min(age_months)),
                                 aes(label = eng_desc))
    })
  },
  
  options = list(height = 700)
)

```

Interactive by category.

```{r, cache=FALSE}
shinyApp(
  ui = fluidPage(
    selectInput("cat_name", "Category:", 
                choices = unique(ms$cat_name)),
    plotOutput("catplot")
  ),
  
  server = function(input, output) {
    output$catplot <- renderPlot({
      ggplot(filter(ms,cat_name == input$cat_name),
             aes(x = age_months, y = answer, col = eng_desc)) + 
        geom_point() + 
        geom_smooth(se=FALSE, method="lm", formula = y ~ log(x)) + 
        scale_colour_solarized(guide=FALSE) + 
        ylim(c(0,1)) + 
        ggrepel::geom_text_repel(data = filter(ms, cat_name == input$cat_name) %>% 
                                   group_by(eng_desc) %>% 
                                   filter(age_months == min(age_months)),
                                 aes(label = eng_desc))
    })
  },
  
  options = list(height = 700)
)
```